apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trilium
  annotations:
    argocd.argoproj.io/sync-wave: '100'
    link.argocd.argoproj.io/application: 'https://trilium.lexrj.com'
spec:
  project: default
  destination:
    name: in-cluster
    namespace: trilium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://trilium-next.github.io/helm-charts
    chart: trilium
    targetRevision: 1.*
    helm:
      values: |
        serviceAccount:
          create: true
        ingress:
          main:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: cloudflare
              nginx.ingress.kubernetes.io/proxy-body-size: '0'
            hosts:
              - host: trilium.lexrj.com
                paths:
                   - path: /
            tls:
              - hosts:
                  - trilium.lexrj.com
              secretName: trilium-server-tls

