apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trilium
  annotations:
    argocd.argoproj.io/sync-wave: '100'
    link.argocd.argoproj.io/application: 'https://trilium.lexrj.com'
spec:
  project: default
  destination:
    name: in-cluster
    namespace: trilium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://triliumnext.github.io/helm-charts
    chart: trilium
    targetRevision: 1.*
    helm:
      valuesObject:
        serviceAccount:
          create: true
        persistence:
          data:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
        ingress:
          main:
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: cloudflare
              nginx.ingress.kubernetes.io/proxy-body-size: '0'
            rules:
              - host: '{{ .Release.Name }}.lexrj.com'
                http:
                  paths:
                    - path: /
                      pathType: PathPrefix
                      backend:
                        service:
                          name: '{{ .Release.Name }}'
                          port:
                            number: '8080'
            tls:
              - hosts:
                  - '{{ .Release.Name }}.lexrj.com'
                secretName: '{{ .Release.Name }}-server-tls'

